name: edt-env
channels:
  - defaults
dependencies:
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - openssl=1.1.1l
  - pip=20.1.1
  - python=3.7.11
  - setuptools=58.0.4
  - sqlite=3.37.0
  - wheel=0.37.0
  - pip:
    - glfw==2.5.0
    - numpy==1.21.5
    - pillow==9.0.0
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
    - ttkbootstrap==1.3.1
